[package]
name = "md2html"
version = "0.12.3-pre"
edition = "2021"
license = "MIT"
rust-version = "1.83"
homepage = "https://github.com/phoepsilonix/md2html"
documentation = "https://github.com/phoepsilonix/md2html"
repository = "https://github.com/phoepsilonix/md2html"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gh-emoji = "1.0.8"
mimalloc-rust = { version = "0.2.1", optional = true }
pico-args = { version = "0.5.0", features = ["combined-flags"] }
pulldown-cmark = { git = "https://github.com/raphlinus/pulldown-cmark.git", branch = "master", default-features = false, features = ["html", "pulldown-cmark-escape"] }

[target.'cfg(any(not(any(target_arch = "arm", target_arch = "aarch64")),all(target_arch = "aarch64", not(target_os = "windows"))))'.dependencies]
mimalloc = { version = "0.1.43", optional = true }


[profile.release]
debug = true
strip = true
lto = true
codegen-units = 1
panic = "abort"
overflow-checks = true

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "fat"

[features]
use-mimalloc-rs = ["dep:mimalloc-rust"]
use-mimalloc = ["dep:mimalloc"]
default = []

